### ISSUE TITLE
 warning  'css' is defined but never used

### ISSUE THREAD

**Issue by guandjoy** [silvenon/gatsby-plugin-linaria#15]
For each usage of css, I'm getting next warning:
`  2:10  warning  'css' is defined but never used  no-unused-vars`

I've tested everything on a plain project:
```javascript
import React from "react"
import { css } from "linaria"

const style = css`
  background-color: red;
`

function Test(props) {
  return <div className={style}>Styled with css</div>
}

export default Test
```

This issue is slowing down my hot reload significantly. How can I fix that?

**Comment by silvenon** [comment]
I think this is because Gatsby comes with a built-in [eslint-loader](https://github.com/webpack-contrib/eslint-loader). Try creating an ESLint config in your project root and set its parser to [babel-eslint](https://github.com/babel/babel-eslint). Also, ensure that you have a Babel configuration as well, which includes `babel-preset-gatsby` and `linaria/babel`.

Btw, I really don't like when tools bundle in eslint-loader, I think ESLint should be opt-in, especially as a webpack loader, which I never want. Now you have to include both ESLint and Babel configuration just to fix a warning which doesn't even indicate a problem. 🙄

Let me know if that worked, in which case I can explain why. 😄

**Comment by silvenon** [comment]
Also, let me know if you need more detailed help with this, in case my instructions weren't clear enough.

**Comment by guandjoy** [comment]
I see. I'll try to fix that and publish results here. Thanks a lot for your help!

**Comment by silvenon** [comment]
It's best to extend [eslint-config-react-app](https://github.com/facebook/create-react-app/tree/master/packages/eslint-config-react-app) because that's the one Gatsby uses [under the hood](https://github.com/gatsbyjs/gatsby/blob/609d6133f94cf10473744a4b952eb6b3e477a174/packages/gatsby/src/utils/eslint-config.js). I tested this locally and it works, I think the difference is that the built-in ESLint configuration isn't able to detect the modified Babel configuration, i.e. it's missing the `linaria/babel` preset, so maybe ESLint somehow ends up linting the code when Linaria already converted calls to `css` into class names, which to ESLint looks like `css` was never used.

I didn't have time to investigate how this happens **exactly**, but I'm sure it's not pretty. 😄 In any case, defining a local ESLint config + Babel config containing `linaria/babel` fixes the problem. Tools like Gatsby are trying to add reasonable defaults, but my opinion is that the appropriate tool to do things like this in an unobtrusive manner doesn't exist yet.

**Comment by silvenon** [comment]
Updated the docs with this info: https://github.com/silvenon/gatsby-plugin-linaria#warning--css-is-defined-but-never-used--no-unused-vars

**Comment by guandjoy** [comment]
It is also possible to fix that by adding a comment to the end of the line.
```javascript
import { css } from 'linaria' // eslint-disable-line
```

But unfortunately, neither of that is making hot reload work faster :(
When I use Linaria inside CRA project (with craco), it is updating styles without page reload. And the styling process is going much quicker. Unfortunately, I don't have time to go deeper with this issue rn.

**Comment by silvenon** [comment]
So just to confirm: hot reloading doesn't work at all? The whole browser is refreshed every time?

**Comment by guandjoy** [comment]
It works but slower than with CRA for like 2 seconds. It's not a big deal. And resolve warnings is actually improving performance a little bit.
 You can clone this rep to feel the difference:  https://github.com/drownbes/linaria-cra
Try to change the color of the link, for example. It updates CSS within 2 seconds even with the bigger project.

**Comment by silvenon** [comment]
I don't have a large Gatsby project with Linaria to compare it with, a new starter project gets hot-reloaded fast. Also, Gatsby and CRA have entirely different webpack configurations, so the hot-reload speed would probably be an issue with Gatsby's internals.

Anyway, thanks for reporting this bug, too bad that this problem required a manual workaround, I'll see if I can figure out why and maybe fix Gatsby itself to avoid this in the future.

**Comment by guandjoy** [comment]
I will try to contribute somehow as soon as I can. Thank you a lot for your great plugin and support.
