### ISSUE TITLE
Option to disable SSR?

### ISSUE THREAD

**Issue by BlackFenix2** [silvenon/gatsby-plugin-linaria#77]
Is there a way to disable SSR for this plugin? Linaria outputs actual .css files rather than adding style tags inline. SSR i feel like this plugin defeats the purpose of using Linaria as an CSS-in-JS solution when the output is similar to Emotion or styled-components.

I switched from Emotion to Linaria to get .css files, i figure .css files are easier to cahce for the client rather than pasting styles on the HTML head tag.

**Comment by BlackFenix2** [comment]
this code doesn't look too much complicated, i can try to submit a PR to add an option to disable the gatsby-srr.js approach through plugin options.

**Comment by silvenon** [comment]
Gatsby injects critical CSS for regular CSS files as well, so giving the option to opt out of this would be inconsistent with that behavior, no? Plus, it's a nice optimization, I didn't quite understand why you would want to disable this, could you explain more?

**Comment by BlackFenix2** [comment]
I figured that the client would have a better UX(User Experience) caching the .css file on repeat visits rather than having to keep requesting the HTML document with inline css each time. wouldn't the HTML Document load slower if i suddenly had 100+ Linaria css classes per page? 

i also realized from inexperience that Gatsby itself inlines CSS, you can close this issue.

**Comment by cometkim** [comment]
@BlackFenix2 the critical css extraction feature is different from Gatsby's default behavior(mini-css-extract for 'all' bundle) because of the concern you mentioned.

See https://github.com/silvenon/gatsby-plugin-linaria/blob/01dbb0b34c/src/gatsby-ssr.js#L44-L45

Only "Critical CSS" is prepended on each page to improve FCP, the rest is not used, and the full stylesheet is recycled for cache hits.
